# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/monty/git/blank-sdl-emscripten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/monty/git/blank-sdl-emscripten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monty/git/blank-sdl-emscripten/CMakeFiles /Users/monty/git/blank-sdl-emscripten/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monty/git/blank-sdl-emscripten/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

SoundSystem/NullMusic.o: SoundSystem/NullMusic.c.o

.PHONY : SoundSystem/NullMusic.o

# target to build an object file
SoundSystem/NullMusic.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SoundSystem/NullMusic.c.o
.PHONY : SoundSystem/NullMusic.c.o

SoundSystem/NullMusic.i: SoundSystem/NullMusic.c.i

.PHONY : SoundSystem/NullMusic.i

# target to preprocess a source file
SoundSystem/NullMusic.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SoundSystem/NullMusic.c.i
.PHONY : SoundSystem/NullMusic.c.i

SoundSystem/NullMusic.s: SoundSystem/NullMusic.c.s

.PHONY : SoundSystem/NullMusic.s

# target to generate assembly for a file
SoundSystem/NullMusic.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SoundSystem/NullMusic.c.s
.PHONY : SoundSystem/NullMusic.c.s

SoundSystem/PCMAudio.o: SoundSystem/PCMAudio.c.o

.PHONY : SoundSystem/PCMAudio.o

# target to build an object file
SoundSystem/PCMAudio.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SoundSystem/PCMAudio.c.o
.PHONY : SoundSystem/PCMAudio.c.o

SoundSystem/PCMAudio.i: SoundSystem/PCMAudio.c.i

.PHONY : SoundSystem/PCMAudio.i

# target to preprocess a source file
SoundSystem/PCMAudio.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SoundSystem/PCMAudio.c.i
.PHONY : SoundSystem/PCMAudio.c.i

SoundSystem/PCMAudio.s: SoundSystem/PCMAudio.c.s

.PHONY : SoundSystem/PCMAudio.s

# target to generate assembly for a file
SoundSystem/PCMAudio.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SoundSystem/PCMAudio.c.s
.PHONY : SoundSystem/PCMAudio.c.s

base3d/src/CPackedFileReader.o: base3d/src/CPackedFileReader.c.o

.PHONY : base3d/src/CPackedFileReader.o

# target to build an object file
base3d/src/CPackedFileReader.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CPackedFileReader.c.o
.PHONY : base3d/src/CPackedFileReader.c.o

base3d/src/CPackedFileReader.i: base3d/src/CPackedFileReader.c.i

.PHONY : base3d/src/CPackedFileReader.i

# target to preprocess a source file
base3d/src/CPackedFileReader.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CPackedFileReader.c.i
.PHONY : base3d/src/CPackedFileReader.c.i

base3d/src/CPackedFileReader.s: base3d/src/CPackedFileReader.c.s

.PHONY : base3d/src/CPackedFileReader.s

# target to generate assembly for a file
base3d/src/CPackedFileReader.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CPackedFileReader.c.s
.PHONY : base3d/src/CPackedFileReader.c.s

base3d/src/CRenderer.o: base3d/src/CRenderer.c.o

.PHONY : base3d/src/CRenderer.o

# target to build an object file
base3d/src/CRenderer.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer.c.o
.PHONY : base3d/src/CRenderer.c.o

base3d/src/CRenderer.i: base3d/src/CRenderer.c.i

.PHONY : base3d/src/CRenderer.i

# target to preprocess a source file
base3d/src/CRenderer.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer.c.i
.PHONY : base3d/src/CRenderer.c.i

base3d/src/CRenderer.s: base3d/src/CRenderer.c.s

.PHONY : base3d/src/CRenderer.s

# target to generate assembly for a file
base3d/src/CRenderer.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer.c.s
.PHONY : base3d/src/CRenderer.c.s

base3d/src/CRenderer_Rasterization.o: base3d/src/CRenderer_Rasterization.c.o

.PHONY : base3d/src/CRenderer_Rasterization.o

# target to build an object file
base3d/src/CRenderer_Rasterization.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer_Rasterization.c.o
.PHONY : base3d/src/CRenderer_Rasterization.c.o

base3d/src/CRenderer_Rasterization.i: base3d/src/CRenderer_Rasterization.c.i

.PHONY : base3d/src/CRenderer_Rasterization.i

# target to preprocess a source file
base3d/src/CRenderer_Rasterization.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer_Rasterization.c.i
.PHONY : base3d/src/CRenderer_Rasterization.c.i

base3d/src/CRenderer_Rasterization.s: base3d/src/CRenderer_Rasterization.c.s

.PHONY : base3d/src/CRenderer_Rasterization.s

# target to generate assembly for a file
base3d/src/CRenderer_Rasterization.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer_Rasterization.c.s
.PHONY : base3d/src/CRenderer_Rasterization.c.s

base3d/src/CRenderer_Tesselation.o: base3d/src/CRenderer_Tesselation.c.o

.PHONY : base3d/src/CRenderer_Tesselation.o

# target to build an object file
base3d/src/CRenderer_Tesselation.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer_Tesselation.c.o
.PHONY : base3d/src/CRenderer_Tesselation.c.o

base3d/src/CRenderer_Tesselation.i: base3d/src/CRenderer_Tesselation.c.i

.PHONY : base3d/src/CRenderer_Tesselation.i

# target to preprocess a source file
base3d/src/CRenderer_Tesselation.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer_Tesselation.c.i
.PHONY : base3d/src/CRenderer_Tesselation.c.i

base3d/src/CRenderer_Tesselation.s: base3d/src/CRenderer_Tesselation.c.s

.PHONY : base3d/src/CRenderer_Tesselation.s

# target to generate assembly for a file
base3d/src/CRenderer_Tesselation.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/CRenderer_Tesselation.c.s
.PHONY : base3d/src/CRenderer_Tesselation.c.s

base3d/src/FixP.o: base3d/src/FixP.c.o

.PHONY : base3d/src/FixP.o

# target to build an object file
base3d/src/FixP.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/FixP.c.o
.PHONY : base3d/src/FixP.c.o

base3d/src/FixP.i: base3d/src/FixP.c.i

.PHONY : base3d/src/FixP.i

# target to preprocess a source file
base3d/src/FixP.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/FixP.c.i
.PHONY : base3d/src/FixP.c.i

base3d/src/FixP.s: base3d/src/FixP.c.s

.PHONY : base3d/src/FixP.s

# target to generate assembly for a file
base3d/src/FixP.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/FixP.c.s
.PHONY : base3d/src/FixP.c.s

base3d/src/Globals.o: base3d/src/Globals.c.o

.PHONY : base3d/src/Globals.o

# target to build an object file
base3d/src/Globals.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/Globals.c.o
.PHONY : base3d/src/Globals.c.o

base3d/src/Globals.i: base3d/src/Globals.c.i

.PHONY : base3d/src/Globals.i

# target to preprocess a source file
base3d/src/Globals.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/Globals.c.i
.PHONY : base3d/src/Globals.c.i

base3d/src/Globals.s: base3d/src/Globals.c.s

.PHONY : base3d/src/Globals.s

# target to generate assembly for a file
base3d/src/Globals.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/Globals.c.s
.PHONY : base3d/src/Globals.c.s

base3d/src/LoadBitmap.o: base3d/src/LoadBitmap.c.o

.PHONY : base3d/src/LoadBitmap.o

# target to build an object file
base3d/src/LoadBitmap.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/LoadBitmap.c.o
.PHONY : base3d/src/LoadBitmap.c.o

base3d/src/LoadBitmap.i: base3d/src/LoadBitmap.c.i

.PHONY : base3d/src/LoadBitmap.i

# target to preprocess a source file
base3d/src/LoadBitmap.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/LoadBitmap.c.i
.PHONY : base3d/src/LoadBitmap.c.i

base3d/src/LoadBitmap.s: base3d/src/LoadBitmap.c.s

.PHONY : base3d/src/LoadBitmap.s

# target to generate assembly for a file
base3d/src/LoadBitmap.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/LoadBitmap.c.s
.PHONY : base3d/src/LoadBitmap.c.s

base3d/src/SDLVersion/CSDL2Renderer.o: base3d/src/SDLVersion/CSDL2Renderer.c.o

.PHONY : base3d/src/SDLVersion/CSDL2Renderer.o

# target to build an object file
base3d/src/SDLVersion/CSDL2Renderer.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/SDLVersion/CSDL2Renderer.c.o
.PHONY : base3d/src/SDLVersion/CSDL2Renderer.c.o

base3d/src/SDLVersion/CSDL2Renderer.i: base3d/src/SDLVersion/CSDL2Renderer.c.i

.PHONY : base3d/src/SDLVersion/CSDL2Renderer.i

# target to preprocess a source file
base3d/src/SDLVersion/CSDL2Renderer.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/SDLVersion/CSDL2Renderer.c.i
.PHONY : base3d/src/SDLVersion/CSDL2Renderer.c.i

base3d/src/SDLVersion/CSDL2Renderer.s: base3d/src/SDLVersion/CSDL2Renderer.c.s

.PHONY : base3d/src/SDLVersion/CSDL2Renderer.s

# target to generate assembly for a file
base3d/src/SDLVersion/CSDL2Renderer.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base3d/src/SDLVersion/CSDL2Renderer.c.s
.PHONY : base3d/src/SDLVersion/CSDL2Renderer.c.s

menu/src/CreditsScreen.o: menu/src/CreditsScreen.c.o

.PHONY : menu/src/CreditsScreen.o

# target to build an object file
menu/src/CreditsScreen.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/CreditsScreen.c.o
.PHONY : menu/src/CreditsScreen.c.o

menu/src/CreditsScreen.i: menu/src/CreditsScreen.c.i

.PHONY : menu/src/CreditsScreen.i

# target to preprocess a source file
menu/src/CreditsScreen.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/CreditsScreen.c.i
.PHONY : menu/src/CreditsScreen.c.i

menu/src/CreditsScreen.s: menu/src/CreditsScreen.c.s

.PHONY : menu/src/CreditsScreen.s

# target to generate assembly for a file
menu/src/CreditsScreen.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/CreditsScreen.c.s
.PHONY : menu/src/CreditsScreen.c.s

menu/src/HelpScreen.o: menu/src/HelpScreen.c.o

.PHONY : menu/src/HelpScreen.o

# target to build an object file
menu/src/HelpScreen.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/HelpScreen.c.o
.PHONY : menu/src/HelpScreen.c.o

menu/src/HelpScreen.i: menu/src/HelpScreen.c.i

.PHONY : menu/src/HelpScreen.i

# target to preprocess a source file
menu/src/HelpScreen.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/HelpScreen.c.i
.PHONY : menu/src/HelpScreen.c.i

menu/src/HelpScreen.s: menu/src/HelpScreen.c.s

.PHONY : menu/src/HelpScreen.s

# target to generate assembly for a file
menu/src/HelpScreen.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/HelpScreen.c.s
.PHONY : menu/src/HelpScreen.c.s

menu/src/Interrogation.o: menu/src/Interrogation.c.o

.PHONY : menu/src/Interrogation.o

# target to build an object file
menu/src/Interrogation.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/Interrogation.c.o
.PHONY : menu/src/Interrogation.c.o

menu/src/Interrogation.i: menu/src/Interrogation.c.i

.PHONY : menu/src/Interrogation.i

# target to preprocess a source file
menu/src/Interrogation.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/Interrogation.c.i
.PHONY : menu/src/Interrogation.c.i

menu/src/Interrogation.s: menu/src/Interrogation.c.s

.PHONY : menu/src/Interrogation.s

# target to generate assembly for a file
menu/src/Interrogation.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/Interrogation.c.s
.PHONY : menu/src/Interrogation.c.s

menu/src/Main.o: menu/src/Main.c.o

.PHONY : menu/src/Main.o

# target to build an object file
menu/src/Main.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/Main.c.o
.PHONY : menu/src/Main.c.o

menu/src/Main.i: menu/src/Main.c.i

.PHONY : menu/src/Main.i

# target to preprocess a source file
menu/src/Main.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/Main.c.i
.PHONY : menu/src/Main.c.i

menu/src/Main.s: menu/src/Main.c.s

.PHONY : menu/src/Main.s

# target to generate assembly for a file
menu/src/Main.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/Main.c.s
.PHONY : menu/src/Main.c.s

menu/src/MainMenu.o: menu/src/MainMenu.c.o

.PHONY : menu/src/MainMenu.o

# target to build an object file
menu/src/MainMenu.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/MainMenu.c.o
.PHONY : menu/src/MainMenu.c.o

menu/src/MainMenu.i: menu/src/MainMenu.c.i

.PHONY : menu/src/MainMenu.i

# target to preprocess a source file
menu/src/MainMenu.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/MainMenu.c.i
.PHONY : menu/src/MainMenu.c.i

menu/src/MainMenu.s: menu/src/MainMenu.c.s

.PHONY : menu/src/MainMenu.s

# target to generate assembly for a file
menu/src/MainMenu.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/MainMenu.c.s
.PHONY : menu/src/MainMenu.c.s

menu/src/UI.o: menu/src/UI.c.o

.PHONY : menu/src/UI.o

# target to build an object file
menu/src/UI.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/UI.c.o
.PHONY : menu/src/UI.c.o

menu/src/UI.i: menu/src/UI.c.i

.PHONY : menu/src/UI.i

# target to preprocess a source file
menu/src/UI.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/UI.c.i
.PHONY : menu/src/UI.c.i

menu/src/UI.s: menu/src/UI.c.s

.PHONY : menu/src/UI.s

# target to generate assembly for a file
menu/src/UI.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/menu/src/UI.c.s
.PHONY : menu/src/UI.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... game"
	@echo "... SoundSystem/NullMusic.o"
	@echo "... SoundSystem/NullMusic.i"
	@echo "... SoundSystem/NullMusic.s"
	@echo "... SoundSystem/PCMAudio.o"
	@echo "... SoundSystem/PCMAudio.i"
	@echo "... SoundSystem/PCMAudio.s"
	@echo "... base3d/src/CPackedFileReader.o"
	@echo "... base3d/src/CPackedFileReader.i"
	@echo "... base3d/src/CPackedFileReader.s"
	@echo "... base3d/src/CRenderer.o"
	@echo "... base3d/src/CRenderer.i"
	@echo "... base3d/src/CRenderer.s"
	@echo "... base3d/src/CRenderer_Rasterization.o"
	@echo "... base3d/src/CRenderer_Rasterization.i"
	@echo "... base3d/src/CRenderer_Rasterization.s"
	@echo "... base3d/src/CRenderer_Tesselation.o"
	@echo "... base3d/src/CRenderer_Tesselation.i"
	@echo "... base3d/src/CRenderer_Tesselation.s"
	@echo "... base3d/src/FixP.o"
	@echo "... base3d/src/FixP.i"
	@echo "... base3d/src/FixP.s"
	@echo "... base3d/src/Globals.o"
	@echo "... base3d/src/Globals.i"
	@echo "... base3d/src/Globals.s"
	@echo "... base3d/src/LoadBitmap.o"
	@echo "... base3d/src/LoadBitmap.i"
	@echo "... base3d/src/LoadBitmap.s"
	@echo "... base3d/src/SDLVersion/CSDL2Renderer.o"
	@echo "... base3d/src/SDLVersion/CSDL2Renderer.i"
	@echo "... base3d/src/SDLVersion/CSDL2Renderer.s"
	@echo "... menu/src/CreditsScreen.o"
	@echo "... menu/src/CreditsScreen.i"
	@echo "... menu/src/CreditsScreen.s"
	@echo "... menu/src/HelpScreen.o"
	@echo "... menu/src/HelpScreen.i"
	@echo "... menu/src/HelpScreen.s"
	@echo "... menu/src/Interrogation.o"
	@echo "... menu/src/Interrogation.i"
	@echo "... menu/src/Interrogation.s"
	@echo "... menu/src/Main.o"
	@echo "... menu/src/Main.i"
	@echo "... menu/src/Main.s"
	@echo "... menu/src/MainMenu.o"
	@echo "... menu/src/MainMenu.i"
	@echo "... menu/src/MainMenu.s"
	@echo "... menu/src/UI.o"
	@echo "... menu/src/UI.i"
	@echo "... menu/src/UI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

