CXX = clang++ -std=c++14
INCLUDES= -Iinclude
CXXFLAGS = -g $(INCLUDES)
SRCM= tests/TestTrivial.cpp src/CGame.cpp  src/CGameSnapshot.cpp
OBJM = $(SRCM:.cpp=.o)
LINKFLAGS= -lcppunit

unittest: tests/TestTrivial.cpp $(OBJM)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJM) $(LINKFLAGS) $(LINKFLAGSLOG4) $(LIBLOG)

# Default compile

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@
