CXX = em++
CXXFLAGS = -g  --preload-file res --use-preload-plugins -Iinclude -std=c++14

OBJS = src/CGame.o src/CGameSnapshot.o SDLVersion/CSDLRenderer.o SDLVersion/main.o


TARGET = game.html

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(CXXFLAGS)

all:   $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	rm game.data
	rm game.js	